# Generated by Django 5.2.14 on 2026-05-23 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='文献标题')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='年份')),
                ('category', models.CharField(choices=[('machine-learning', '机器学习'), ('computer-vision', '计算机视觉'), ('natural-language', '自然语言处理'), ('optimization', '优化算法'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文献资料',
                'verbose_name_plural': '文献资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='便签内容')),
                ('files', models.JSONField(default=list, verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '灵感便签',
                'verbose_name_plural': '灵感便签',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='notes/%Y/%m/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_data', to='backend.note')),
            ],
            options={
                'verbose_name': '便签附件',
                'verbose_name_plural': '便签附件',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('suspended', '已暂停')], default='ongoing', max_length=20, verbose_name='状态')),
                ('documents', models.JSONField(default=list, verbose_name='文档列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('doc_type', models.CharField(max_length=50, verbose_name='文档类型')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_files', to='backend.project')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='赛事名称')),
                ('grades', models.JSONField(default=list, verbose_name='适用年级')),
                ('description', models.TextField(blank=True, verbose_name='赛事描述')),
                ('timeline_note', models.TextField(blank=True, verbose_name='时间线备注')),
                ('stages', models.JSONField(default=list, verbose_name='赛程阶段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '赛程规划',
                'verbose_name_plural': '赛程规划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='待办内容')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_mode', models.CharField(default='grid', max_length=20, verbose_name='视图模式')),
                ('last_category', models.CharField(default='all', max_length=50, verbose_name='上次分类')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100, verbose_name='学校')),
                ('college', models.CharField(default='', max_length=100, verbose_name='学院')),
                ('major', models.CharField(default='', max_length=100, verbose_name='专业')),
                ('grade', models.CharField(default='', max_length=20, verbose_name='年级')),
                ('grade_detail', models.CharField(default='', max_length=20, verbose_name='年级详情')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='WorkbenchFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='文件名')),
                ('original_name', models.CharField(max_length=300, verbose_name='原始文件名')),
                ('file', models.FileField(upload_to='workbench/%Y/%m/', verbose_name='文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('content_type', models.CharField(default='', max_length=100, verbose_name='MIME类型')),
                ('file_type', models.CharField(default='file', max_length=20, verbose_name='文件分类(image/pdf/doc/other)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbench_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作台文件',
                'verbose_name_plural': '工作台文件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('treasure', '科研宝藏库'), ('competition', '学科竞赛')], max_length=50, verbose_name='来源分类')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('source_url', models.CharField(blank=True, max_length=500, verbose_name='来源链接')),
                ('favorited_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-favorited_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
